language: php
cache: bundler
php:
  - '7.1'

before_script:
  - bundle install
  - mkdir -p _data

script:
  - php news.php
  - bundler exec jekyll build
  - echo "forestguild.club" > _site/CNAME

after_script:
  - cat _data/news.csv

deploy:
  provider: pages
  skip-cleanup: true
  github-token: $GITHUB_API_KEY  # Set in the settings page of your repository, as a secure variable
  keep-history: false
  local-dir: _site
  on:
    branch: master
