language: php
cache: bundler
php:
  - '7.1'

before_script:
  - bundle install
  - mkdir -p _data

script:
  - php news.php
  - bundler exec jekyll build
  - echo "forestguild.club" > _site/CNAME

after_script:
  - cat _data/news.csv

deploy:
  provider: pages
  skip-cleanup: true
  github-token: $GITHUB_API_KEY
  keep-history: false
  local-dir: _site
  on:
    branch: master

after_deploy:
  - "curl -sX POST 'https://api.cloudflare.com/client/v4/zones/$CF_ZONE_ID/purge_cache' -H 'X-Auth-Email: $CF_API_EMAIL' -H 'X-Auth-Key: $CF_API_TOKEN' -H 'Content-Type: application/json' -d '{\"purge_everything\":true}'"
